services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - ./frontend/dist:/usr/src/app/frontend/dist
    command: flask run --host=0.0.0.0